# version: "3"

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "5000:5000"
#     environment:
#       - DB_HOST=localhost
#       - DB_PORT=3306
#       - DB_USER=root
#       - DB_PASSWORD=root_password
#       - DB_NAME=db_demo

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://username:password@postgres:5432/mydb"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
