version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=db_demo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
