name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (for any build steps)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build the backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t backend ./backend

      # Step 5: Build the frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t frontend ./frontend

      # Step 6: Set up DockerHub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Backend Docker image to Docker Hub
      - name: Push Backend Docker image to Docker Hub
        run: |
          docker tag backend:latest ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Step 8: Push Frontend Docker image to Docker Hub
      - name: Push Frontend Docker image to Docker Hub
        run: |
          docker tag frontend:latest ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Step 9: Install Render CLI
      - name: Install Render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh
        shell: bash

      # Step 10: Authenticate with Render CLI using API token
      - name: Authenticate with Render CLI
        run: |
          echo "${{ secrets.RENDER_API_TOKEN }}" | render login
        shell: bash

      # Step 11: Redeploy Backend Service on Render (to update the Docker image)
      - name: Redeploy Backend Service on Render
        run: |
          render services redeploy noted-app-server -o json
        shell: bash

      # Step 12: Redeploy Frontend Service on Render (to update the Docker image)
      - name: Redeploy Frontend Service on Render
        run: |
          render services redeploy noted-app-client -o json
        shell: bash

      # Step 13: Finalize and clean up
      - name: Cleanup
        run: |
          docker system prune -f
        shell: bash
